


// RETRIEVEDATA FROM DROPDOWN MENUS(PRICE,ACTIVITY TYPE, #OF PEOPLE) FOR SUBMISSION TO BORED API
// USING DATA RETRIVED FROM MENUS, STORE IN VARIABLES TO USE AS SEARCH PARAMETERS
// IF USER CLICKS RANDOMIZE BUTTON SUGGEST COMPLETELY RANDOM ACTIVITY FROM BORED API
//
// FETCH DATA FROM BORED API TO SUGGEST DATE BASED ON USERS INPUT
// DISPLAY DATA IN A PARAGRAPH ELEMENT IN THE MAIN SECTION
// INITIZALE BOREDAPI APP
//HOW BORED API DATA IS PRESENTED
// {
// 	"activity":"Learn a new recipe",
// 	"accessibility":0.05,
// 	"type":"cooking",
// 	"participants":1,
// 	"price":0
// }


//STRETCH GOAL API
// DISPLAY WEATHER IN TORONTO
// DISPLAY WEATHER INFORMATION FOR THE CURRENT DAY (MAYBE THE USER WOULD LIKE TO RETHINK THEIR DATE IF IT'S RAINING)
// MORE STRETCH: DISPLAY WEATHER TOP OF THE FORM FOR THE WEEK SO THE USER CAN PLAN THERE FUTURE DATE






// HOW SEARCH PARAMS ARE SETUP
//http://www.boredapi.com/documentation
//url:http://www.boredapi.com/api/

//random == http://www.boredapi.com/api/activity/
//#of people == /activity?participants=1
//price == /activity?price=0.0 =>with a a
